In [2]:
distance=[56,89,45,75,68]
time=[0.3,2.1,1.3,1.9,3.2]

In [3]:
speed=distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
distance*3

[56, 89, 45, 75, 68, 56, 89, 45, 75, 68, 56, 89, 45, 75, 68]

In [5]:
distance+time

[56, 89, 45, 75, 68, 0.3, 2.1, 1.3, 1.9, 3.2]

In [9]:
import numpy as np

In [10]:
dist_array=np.array(distance)
time_array=np.array(time)

In [11]:
speed=dist_array/time_array
speed

array([186.66666667,  42.38095238,  34.61538462,  39.47368421,
        21.25      ])

In [12]:
### arrays are data structures which can be created using the numpy package. It supports mixed data types.

In [13]:
print(type(dist_array))

<class 'numpy.ndarray'>


##### We combine 0D arrays to get a 1D array,we combine 1D arrays to get a 2D array. And we combine 2D arrays to get a 3D array.

In [14]:
###0D arrays-
array_0D=np.array(90)
print(type(array_0D))
print(array_0D.ndim)


<class 'numpy.ndarray'>
0


In [17]:
###1D array:
array_1d=np.array([7,9,2,13.5],dtype='float')
print(type(array_1d))
print(array_1d.ndim)
print(array_1d)
print(array_1d.dtype)

<class 'numpy.ndarray'>
1
[ 7.   9.   2.  13.5]
float64


In [19]:
####2D array-:
array_2D=np.array([[3,5,6,7,8],[9,10,11,12,13],[0,5,1,3,8]])
print(array_2D)
print(array_2D.ndim)
print(array_2D.dtype)
print(array_2D.shape)
print(array_2D.size)

[[ 3  5  6  7  8]
 [ 9 10 11 12 13]
 [ 0  5  1  3  8]]
2
int32
(3, 5)
15


In [20]:
array_3d=np.array([[[3,4,5],[6,7,8]],[[9,10,11],[12,13,14]]])
print(array_3d)
print(array_3d.ndim)
print(array_3d.dtype)
print(array_3d.shape)
print(array_3d.size)

[[[ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]]]
3
int32
(2, 2, 3)
12


#### Conversion of a lower dimensional array to a higher dimensional array,by adding dimensions.

In [23]:
arr1d=np.array([2,3,4,5,6,7,8,9,10,11,12,13])
print(arr1d)
print(arr1d.ndim)
print(arr1d.size)
print(arr1d.dtype)
print(arr1d.shape)

[ 2  3  4  5  6  7  8  9 10 11 12 13]
1
12
int32
(12,)


In [22]:
arr2d=arr1d.reshape(6,2)
print(arr2d)
print(arr2d.ndim)
print(arr2d.size)
print(arr2d.dtype)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
2
12
int32


In [24]:
arr1d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
##convert to a 3D array:
arr3d=arr1d.reshape(3,2,2)
print(arr3d)
print(arr3d.ndim)
print(arr3d.size)
print(arr3d.dtype)

[[[ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]
3
12
int32


In [26]:
###Q) create a 1D array with first 9 natural numbers. Then add a dimension to convert the same to a 2D array.

In [37]:
arr6=np.arange(1,10)
print(arr6)
reshaped_arr6=np.reshape(arr6,(3,3))
print(reshaped_arr6)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
####Q) create a 2D array with 6 rows and 3 columns . reshape it to a 3D array

### we have a module called 'random' which provides functions for generating random numbers from a standard normal dist,a standard normal dist have 0 mean and std=1

In [41]:
arr7=np.random.rand(6,3)
print(arr7)      #all the random numbers we got will lie between 0 and 1

print('------------------------------')
reshaped_arr7=arr7.reshape(2,3,3)
print(reshaped_arr7)

[[0.13248196 0.78922048 0.90939262]
 [0.15527765 0.62357934 0.32651432]
 [0.64253794 0.41180134 0.81394446]
 [0.1013889  0.24728158 0.94971384]
 [0.47151377 0.97334275 0.62191843]
 [0.61436758 0.91196283 0.23616351]]
------------------------------
[[[0.13248196 0.78922048 0.90939262]
  [0.15527765 0.62357934 0.32651432]
  [0.64253794 0.41180134 0.81394446]]

 [[0.1013889  0.24728158 0.94971384]
  [0.47151377 0.97334275 0.62191843]
  [0.61436758 0.91196283 0.23616351]]]


#### Convert a higher dimentional array to a lower dimentional array- we use two functions ravel() and flatten().

In [29]:
arr_lowerd=arr3d.flatten()
arr_lowerd

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
arr_lowerdd=arr2d.ravel()
arr_lowerdd

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [31]:
#create two arrays one having elements 30,20,10 and the second having elements 40,50,60 and perform the basic mathematical
#operations.

In [34]:
a = np.array([30,20,10])
b = np.array([40,50,60])
sum = a+b
mult = a*b
div = b/a
sub = b-a
print(f"sum = {sum}\nmultiplication = {mult}\ndivision = {div}\nsubtraction = {sub}")

sum = [70 70 70]
multiplication = [1200 1000  600]
division = [1.33333333 2.5        6.        ]
subtraction = [10 30 50]


In [32]:
###statistical operations-:
array4=np.array([[4,3,2],[10,1,0],[5,8,24]])
array4

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [33]:
####perform basic statistical operations like mean,median,std,var.

In [35]:
mean = np.mean(array4)
median = np.median(array4)
std = np.std(array4)
var = np.var(array4)
print(f"array = {array4}\nmean = {mean}\nmedian = {median}\nstandard deviation = {std}\nvariance = {var}")

array = [[ 4  3  2]
 [10  1  0]
 [ 5  8 24]]
mean = 6.333333333333333
median = 4.0
standard deviation = 6.944222218666553
variance = 48.22222222222222


##### Indexing

In [2]:
import numpy as np

In [3]:
arr_1d=np.array([1,2,3,4,5])

In [4]:
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
###print 4 from the 1D array:
print(arr_1d[3])
print(arr_1d[-2])

4
4


In [7]:
### find out the sum of the 4th and 2nd element of the 1d array:
sum1=arr_1d[3]+arr_1d[1]
sum1


6

In [8]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
### how do i slice 3(3rd element of the first row)
arr_2d[0,2]

3

In [10]:
### how do i slice 14 from arr_2d?
arr_2d[2,3]

14

In [11]:
arr_2d[-1,-2]

14

In [12]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [13]:
###slice out 16 from arr_3d
arr_3d[2,1,0]

16

In [14]:
###Q)slice out 7,10,9,12 from the 3D array

In [15]:
seven=arr_3d[1,0,0]
ten=arr_3d[1,1,0]
nine=arr_3d[1,0,2]
twelve=arr_3d[1,1,2]

print(seven,ten,nine,twelve)

7 10 9 12


In [15]:
###Q) slice out the second row (10,11,12) from arr_3d

In [16]:
res=arr_3d[1,1:]
res

array([[10, 11, 12]])

In [17]:
arr_3d[1,1,:]

array([10, 11, 12])

In [19]:
arr_3d[1,0:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [18]:
arr_3d[1,1]

array([10, 11, 12])

#### Slicing creates a view of the original array. indexing on the other hand creates a copy of the original array.

In [20]:
x=np.array([4,5,6])

In [21]:
y=x.copy()

In [22]:
x[1]=10

In [23]:
x

array([ 4, 10,  6])

In [24]:
y

array([4, 5, 6])

In [25]:
###copy is independent of the original array.

In [26]:
z=x.view()

In [27]:
x[-1]=60

In [28]:
x

array([ 4, 10, 60])

In [29]:
z

array([ 4, 10, 60])

In [30]:
y

array([4, 5, 6])

In [31]:
### view is dependent on the original array. if we make any changes in the original array,the view gets impacted.

In [32]:
employee_rating=np.array([1,4,3,5,6,8,9,10,12])

In [33]:
###I want 4-9 elements to be sliced out from employee rating.
employee_rating[1:7]

array([4, 3, 5, 6, 8, 9])

In [ ]:
###step method:
#syntax=[start:stop:step]

In [34]:
employee_rating[1:6:3]

array([4, 6])

In [35]:
employee_rating[1:6:2]

array([4, 5, 8])

In [36]:
employee_rating[2:8:1]

array([ 3,  5,  6,  8,  9, 10])

In [37]:
#### we use the step method when we want to skip elements while reading within a specific range. we will
#### always skip=step-1 elements.

In [38]:
### Q) i want only 1 and 6 sliced out from employee rating.
employee_rating

array([ 1,  4,  3,  5,  6,  8,  9, 10, 12])

In [39]:
employee_rating[0:5:4]

array([1, 6])

In [40]:
employee_rating[:8:4]

array([1, 6])

In [42]:
a1=np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [43]:
###Q)slice out 14 and 16 from the array a1

In [45]:
####Q) slice out 11,14,17 using the step method from a1

In [50]:
print(a1[14:17:2])
print(a1[-7:-4:2])

[14 16]
[14 16]


In [47]:
a1[11:18:3]

array([11, 14, 17])

In [51]:
a1[-10:-3:3]

array([11, 14, 17])

In [52]:
### Print all the elements of a1 in the reverse order

In [55]:
reverse = a1[::-1]
print(reverse)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [53]:
### create an array with elements 1,2,3,4 and slice out 2,4 using the step method.

In [57]:
a2 = np.array([1,2,3,4])
print(a2[1::2])

[2 4]


In [54]:
### slice out 3,4 from the above array using negetive slicing.

In [59]:
print(a1[-2:])

[3 4]


In [60]:
print(a1[-2::1])

[3 4]


#### As a data scientist,your task is to create a python object that explores numpy's attributes and functions.Use the dataset containing daily temperature records for a week
* temperatures=[76.2,78.2,74.5,79.3,82.6,79.8,66.5,71.6]
* 1) Explore the key attributes-ndim,shape,size
* 2) demonstrate numpy array functions like reshape,flatten,transpose.

In [54]:
temperatures=[76.2,78.2,74.5,79.3,82.6,79.8,66.5,71.6]
temp = np.array(temperatures)
#1
dimension = temp.ndim 
shape = temp.shape
size = temp.size
print(f"dimension = {dimension}\nshape = {shape}\nsize = {size}")
#2
two_d = temp.reshape(2,4)
three_d = temp.reshape(2,2,2)
flat = three_d.flatten()
trans = np.transpose(two_d)
print(f"Reshaping to create 2D array \n {two_d}\nReshaping to create 3D array \n{three_d}\n\nUsing flatten to create 1D array = {flat}\nTranspose\n{trans}")

dimension = 1
shape = (8,)
size = 8
Reshaping to create 2D array 
 [[76.2 78.2 74.5 79.3]
 [82.6 79.8 66.5 71.6]]
Reshaping to create 3D array 
[[[76.2 78.2]
  [74.5 79.3]]

 [[82.6 79.8]
  [66.5 71.6]]]

Using flatten to create 1D array = [76.2 78.2 74.5 79.3 82.6 79.8 66.5 71.6]
Transpose
[[76.2 82.6]
 [78.2 79.8]
 [74.5 66.5]
 [79.3 71.6]]


###### Q)Create a 3D array using elements from 5-16,convert it to a 2D array and finally to a 1D array using the flatten method

In [53]:
array_3d=np.arange(5,17).reshape(2,3,2)

#convert it to a 2D array:

array_2d=array_3d.reshape(6,2)

#convert it to a 1D array:

array_1d=array_2d.flatten()


print(array_3d)
print(array_2d)
print(array_1d)

[[[ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]]]
[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[ 5  6  7  8  9 10 11 12 13 14 15 16]


#### Q)Check if the values 15,20,25 are present in the above array you have created.

#### Q) array_test=np.array(1,1,1,2,4,8,9,2,4,1,6) is a 1D array.Find out the number of elements present in the array and the most frequently occuring element.

#####  bincount function from numpy returns the count of values in each bin starting from 0 to the highest value in the collection.

###### Q) array_1d=np.array([1,2,3,4,5,6]) and create a 3D array with elements 1-18.
* print out the value 15 from the 3D array
* slice out 7,6,11 from the 3D array
* slice out the second row from the first 2D array


##### Q) create an array with the first 30 natural numbers. slice out 12,14,16,18,20,22 using the step method (take a step of 2,and use negetive indices only)

##### Q) print all the elements in the above subset in the reverse order

##### Q) create a numpy array with elements 5-20 and update the values of all elements from the fifth position onwards to 25

##### Q)  modify every second element in the above array and assign a value 16 to it.

#### pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,built on top of the Python programming language.it offers data structures and operations for manipulating numerical data. The two data structures are 1) A 1 dimentional Series 2) A Dataframe

#### Pandas Series() is a function used to generate a series. Creation of a series from a numpy array requires the array() function from the Numpy package.

### Intrinsic data alignment happens with the pandas package. Each data structure has got the internal indexes aligned to each element.

In [1]:
import pandas as pd
import numpy as np

In [2]:
#### series support multiple data types.

In [3]:
ser1=pd.Series([45,89.5,None,True,(5,6),'text'])
ser1

0        45
1      89.5
2      None
3      True
4    (5, 6)
5      text
dtype: object

In [6]:
ser2=pd.Series([45,89.5,None,True,(5,6),'text'],index=['a','b','c','d','e','f'])
ser2

a        45
b      89.5
c      None
d      True
e    (5, 6)
f      text
dtype: object

In [7]:
arr=np.array([34,67,89,12,45.6])
ser3=pd.Series(arr)
ser3

0    34.0
1    67.0
2    89.0
3    12.0
4    45.6
dtype: float64

In [8]:
t1=(34,67,89,12,45.6)
ser4=pd.Series(t1)
ser4

0    34.0
1    67.0
2    89.0
3    12.0
4    45.6
dtype: float64

In [10]:
ser4[3]

12.0

In [13]:
dict1={'a':'apple','b':2426,10875:'employee','language':'python'}
ser5=pd.Series(dict1)
ser5

a              apple
b               2426
10875       employee
language      python
dtype: object

In [11]:
ser5[10875]

'employee'

In [15]:
print(type(ser5))

<class 'pandas.core.series.Series'>


In [14]:
data={'Age':[24,28,31,35,42],
     'Name':['Sim','Tim','Jack','Lisa','Lily'],
      'Marks':[82,85,65,76,91]}

df=pd.DataFrame(data)
print(df)
print(type(df))

   Age  Name  Marks
0   24   Sim     82
1   28   Tim     85
2   31  Jack     65
3   35  Lisa     76
4   42  Lily     91
<class 'pandas.core.frame.DataFrame'>


In [16]:
###Loc function helps us slice dataframes using the row/column labels

In [18]:
df.loc[3,'Name']

'Lisa'

In [19]:
###last 3 rows
df.loc[2:4,:]

Age  Name  Marks
2   31  Jack     65
3   35  Lisa     76
4   42  Lily     91

In [27]:
#last 3 rows using iloc function:
df.iloc[2:,:]

Age  Name  Marks
2   31  Jack     65
3   35  Lisa     76
4   42  Lily     91

In [20]:
###i want the info of jack,lisa and lily but i want only their names and marks.
df.loc[2:,['Name','Marks']]

Name  Marks
2  Jack     65
3  Lisa     76
4  Lily     91

In [21]:
df.loc[2:,'Name':]

Name  Marks
2  Jack     65
3  Lisa     76
4  Lily     91

In [25]:
### say i want a single column from this dataframe.say-age
df.loc[:,['Age']]

Age
0   24
1   28
2   31
3   35
4   42

In [29]:
df.iloc[:,[0]]

Age
0   24
1   28
2   31
3   35
4   42

In [30]:
df.Age

0    24
1    28
2    31
3    35
4    42
Name: Age, dtype: int64

In [31]:
### see all columns in our dataframe
df.columns

Index(['Age', 'Name', 'Marks'], dtype='object')

In [33]:
###slice out the name and age of tim,lisa,lily using loc and iloc

In [34]:
df.iloc[[1, 3, 4], [1, 0]]

Name  Age
1   Tim   28
3  Lisa   35
4  Lily   42

In [36]:
df.loc[(1,3,4),'Age':'Name']

Age  Name
1   28   Tim
3   35  Lisa
4   42  Lily

### Functions of a dataframe:

* tail,head-selectively displays the bottom and top 5 rows of a dataframe.
* sample() functions helps select random rows and columns from a dataframe.
* info() function gives more info on the dataset
* describe() functions gives the summary stats for the variables in the data
* query() functions helps us to query the dataset on some condition
* loc() helps us to query the dataset based on column and row labels
* iloc() helps us to query the dataset based on the index position of rows and columns
* unique() helps us get the distinct values in a certain row or column
* null() helps us to locate missing values
* fillna() helps us to fill missing values in the dataset with some value
* rename() helps us to rename the column name
* where() replaces cells with null values where the where condition is not satisfied
* drop() used  to drop columns/rows from a dataset
* corr() used to find relationships between variables.

In [37]:
data=pd.read_csv('Salary_Data.csv')
print('data is loaded')

data is loaded


In [38]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [39]:
###head function will display the top 5 rows of the dataframe:
data.head(7)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0

In [40]:
#tail function prints the default 5 rows from the bottom:
data.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [41]:
import pandas as pd

In [42]:
###sample:
data.sample(10)

YearsExperience    Salary
22              7.9  101302.0
3               2.0   43525.0
23              8.2  113812.0
17              5.3   83088.0
15              4.9   67938.0
6               3.0   60150.0
24              8.7  109431.0
5               2.9   56642.0
4               2.2   39891.0
25              9.0  105582.0

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes


In [44]:
### describe-:
data.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [45]:
#query:
data.query('YearsExperience>5.5')

YearsExperience    Salary
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [46]:
##### use the loc function to display the salary of the last two employees using the loc and iloc functions.

In [51]:
print(data.loc[28:,['Salary']])
print(data.iloc[[28,29],[1]])

      Salary
28  122391.0
29  121872.0
      Salary
28  122391.0
29  121872.0


In [47]:
###### filter out all those employees with salary greater than 50k and experience less than 3 years using loc function.

In [49]:
data.loc[(data["YearsExperience"] < 3) &(data["Salary"] > 50000),["Salary","YearsExperience"]]

Salary  YearsExperience
5  56642.0              2.9