In [2]:
distance=[56,89,45,75,68]
time=[0.3,2.1,1.3,1.9,3.2]

In [3]:
speed=distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
distance*3

[56, 89, 45, 75, 68, 56, 89, 45, 75, 68, 56, 89, 45, 75, 68]

In [5]:
distance+time

[56, 89, 45, 75, 68, 0.3, 2.1, 1.3, 1.9, 3.2]

In [9]:
import numpy as np

In [10]:
dist_array=np.array(distance)
time_array=np.array(time)

In [11]:
speed=dist_array/time_array
speed

array([186.66666667,  42.38095238,  34.61538462,  39.47368421,
        21.25      ])

In [12]:
### arrays are data structures which can be created using the numpy package. It supports mixed data types.

In [13]:
print(type(dist_array))

<class 'numpy.ndarray'>


##### We combine 0D arrays to get a 1D array,we combine 1D arrays to get a 2D array. And we combine 2D arrays to get a 3D array.

In [14]:
###0D arrays-
array_0D=np.array(90)
print(type(array_0D))
print(array_0D.ndim)


<class 'numpy.ndarray'>
0


In [17]:
###1D array:
array_1d=np.array([7,9,2,13.5],dtype='float')
print(type(array_1d))
print(array_1d.ndim)
print(array_1d)
print(array_1d.dtype)

<class 'numpy.ndarray'>
1
[ 7.   9.   2.  13.5]
float64


In [19]:
####2D array-:
array_2D=np.array([[3,5,6,7,8],[9,10,11,12,13],[0,5,1,3,8]])
print(array_2D)
print(array_2D.ndim)
print(array_2D.dtype)
print(array_2D.shape)
print(array_2D.size)

[[ 3  5  6  7  8]
 [ 9 10 11 12 13]
 [ 0  5  1  3  8]]
2
int32
(3, 5)
15


In [20]:
array_3d=np.array([[[3,4,5],[6,7,8]],[[9,10,11],[12,13,14]]])
print(array_3d)
print(array_3d.ndim)
print(array_3d.dtype)
print(array_3d.shape)
print(array_3d.size)

[[[ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]]]
3
int32
(2, 2, 3)
12


#### Conversion of a lower dimensional array to a higher dimensional array,by adding dimensions.

In [23]:
arr1d=np.array([2,3,4,5,6,7,8,9,10,11,12,13])
print(arr1d)
print(arr1d.ndim)
print(arr1d.size)
print(arr1d.dtype)
print(arr1d.shape)

[ 2  3  4  5  6  7  8  9 10 11 12 13]
1
12
int32
(12,)


In [22]:
arr2d=arr1d.reshape(6,2)
print(arr2d)
print(arr2d.ndim)
print(arr2d.size)
print(arr2d.dtype)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
2
12
int32


In [24]:
arr1d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
##convert to a 3D array:
arr3d=arr1d.reshape(3,2,2)
print(arr3d)
print(arr3d.ndim)
print(arr3d.size)
print(arr3d.dtype)

[[[ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]
3
12
int32


In [26]:
###Q) create a 1D array with first 9 natural numbers. Then add a dimension to convert the same to a 2D array.

In [28]:
####Q) create a 2D array with 6 rows and 3 columns . reshape it to a 3D array

#### Convert a higher dimentional array to a lower dimentional array- we use two functions ravel() and flatten().

In [29]:
arr_lowerd=arr3d.flatten()
arr_lowerd

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
arr_lowerdd=arr2d.ravel()
arr_lowerdd

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [31]:
#create two arrays one having elements 30,20,10 and the second having elements 40,50,60 and perform the basic mathematical
#operations.

In [32]:
###statistical operations-:
array4=np.array([[4,3,2],[10,1,0],[5,8,24]])
array4

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [33]:
####perform basic statistical operations like mean,median,std,var.